### ISSUE TITLE
No scrollbar in Code editor

### ISSUE THREAD

**Issue by quartertone** [standardnotes/code-editor#11]
The scrollbar does not display when using the Code Editor, regardless of language selected. Behavior is consistent whether the note is converted from the Plain Editor, or started fresh with Code Editor as default.

**Comment by mobitar** [comment]
Hmm good catch..

**Comment by ningsongshen** [comment]
Hey @quartertone! The issue was fixed here: 9d63acbc845cf57ecae60483df196444bcdf6fdc
