### ISSUE TITLE
Code editor syntax highlighting doesn't work for 'Rust'

### ISSUE THREAD

**Issue by kit299** [standardnotes/code-editor#15]
When selecting 'Rust' as the language in the Code editor, there is no syntax highlighting.
Example from web demo app.

![rust example, cropped](https://user-images.githubusercontent.com/44656000/83602276-1605ae00-a527-11ea-8cff-38e0f27f38bb.png)

The error `TypeError: CodeMirror.defineSimpleMode is not a function` is shown on the console.

(The same issue occurs in the Windows desktop app)

**Comment by ningsongshen** [comment]
This is also an issue for Dockerfile, Factor, Handlebar, and NSIS.
