### ISSUE TITLE
markdown - comments are treated as headings in code block

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/code-editor#23]
When I write comment in a code block, the editor renders it like it was a heading in Markdown

![image](https://user-images.githubusercontent.com/6804228/91635596-46a39980-e9e9-11ea-83c0-831b041e1f25.png)

I think that markdown formatting should not happen inside a code block.

There is a workaround if text is appended right after the comment with no spaces
![image](https://user-images.githubusercontent.com/6804228/91635661-c7629580-e9e9-11ea-9830-2e816573fa52.png)

**Comment by JaspalSuri** [comment]
Thanks for letting us know! I was able to reproduce this upon setting the language to Markdown as well. I'll be sure to pass this along!

**Comment by johnny243** [comment]
Fixed in #24
