### ISSUE TITLE
reStructuredText  - no syntax highlighting

### ISSUE THREAD

**Issue by triangulum** [standardnotes/code-editor#8]
I write documentation in Sphinx using reStructuredText. While researching about a question or issue, I will make notes, and then copy that information over to the documentation once an initial version is complete.

I thought I would try and use the *Code Editor* to store some of these reST snippets. However, it appears there is limited/buggy syntax highlighting. The highlighting does not match that of Atom or Sublime Text.

Is this a known issue?

**Comment by mobitar** [comment]
We don't develop the language plugins for the code editor. It's part of CodeMirror. I'm afraid I don't know much about reStructuredText. This would be the first I hear about anyone having this particular issue though.

**Comment by triangulum** [comment]
Standard Notes - Code Editor
![screen shot 2018-11-25 at 11 02 47 pm](https://user-images.githubusercontent.com/22440652/48978846-63b98300-f106-11e8-88a8-b909e54b22a4.png)

Atom - One Light theme with reST syntax highlighting
![screen shot 2018-11-25 at 11 03 22 pm](https://user-images.githubusercontent.com/22440652/48978847-64521980-f106-11e8-8fdc-42eaabe91af1.png)

**Comment by mobitar** [comment]
Ah, something's indeed up with the parser for this language:

```
rst.js:65 Uncaught TypeError: CodeMirror.overlayMode is not a function
    at file:///Users/mobitar/Library/Application%20Support/Standard%20Notes/Extensions/org.standardnotes.code-editor/dist/vendor/modes/rst/rst.js:65:21
    at getMode (file:///Users/mobitar/Library/Application%20Support/Standard%20Notes/Extensions/org.standardnotes.code-editor/dist/dist.js:1340:17)
    at loadMode (file:///Users/mobitar/Library/Application%20Support/Standard%20Notes/Extensions/org.standardnotes.code-editor/dist/dist.js:4622:17)
```

Will have to investigate this, but probably won't get the chance until next year. If you'd like to take a look yourself, or if anyone else is willing to contribute, that would be greatly helpful.
